# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@master
      - name: Install sccache
        run: cargo install sccache
        
      - name: Fetch Source
        run: |
          df -h
          cd ~
          git clone https://github.com/capyloon/gecko-b2g -b capyloon --depth=1
          git clone  https://github.com/Web-Spaces/gecko-ci
          cd gecko-ci
          chmod +x build-win.sh
          cp mozconfig-b2g-win-x86_64 ../gecko-b2g
          cp build-win.sh ../gecko-b2g
          
      - name: Bootstrap Gecko
        run: |
          df -h
          cd ~
          curl https://packages.preprod.kaiostech.com/ndk/v7/mozbuild.tar.bz2 | tar -C ${HOME}/ -xj
          rustup target add aarch64-linux-android armv7-linux-androideabi thumbv7neon-linux-androideabi
          pip3 install winreg

      - name: build Gecko
        run: |
          df -h
          cd ~/gecko-b2g
          ./build-win.sh
